### ISSUE TITLE
proposal：能否增加可选参数：seeders_less_than做种人数小于

### ISSUE THREAD

**Issue by Walleloveeve** [xiaohaiGreen/mteam-active-top-rss#2]
您好：
我已经在OMV7上成功运行了该docker镜像，成功获取到RSS地址并添加到qbittorrent中。
运行环境：Linux nas 6.1.0-20-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64 GNU/Linux
但是RSS获取到的种子是所有推荐置顶的种子。

能否添加一个可选条件：
参数：seeders_less_than；
取值：整数；
解释：做种人数小于。
这样就能根据种子当前做种人数来进行筛选，只下载当前做种人数较少的免费置顶种子。
非常感谢！

**Comment by xiaohaiGreen** [comment]
好的，我看下加下

**Comment by Walleloveeve** [comment]
好的，非常感谢！

**Comment by xiaohaiGreen** [comment]
参数已添加，版本1.5以上

**Comment by Walleloveeve** [comment]
非常感谢，我抽空更新后给你反馈结果
