### ISSUE TITLE
建议增加种子链接可选参数：useHttps和type

### ISSUE THREAD

**Issue by Walleloveeve** [xiaohaiGreen/mteam-active-top-rss#4]
大佬你好，我在NAS上部署了该docker，已经稳定运行了1个月，很好用，非常感谢！

还有一个小小的建议，望能采纳：
生成的xml文件中的enclosure url建议增加种子链接可选参数：
1、useHttps     种子链接是否为https，true或false
2、type  种子链接的网络类型，ipv4或ipv6

网站提供的种子下载接口：/api/rss/dlv2是支持这两个参数的，如下图接口所示：
![微信图片_20240720233356](https://github.com/user-attachments/assets/7e7a04cf-0156-4ca4-ac58-e2f3654e9bd2)

添加这两个参数后，对于突破国内运营商的封锁非常有用，使用https和ipv6在墙内可以连接到更多的用户，从而提高下载和上传速度。

**Comment by xiaohaiGreen** [comment]
好的，我看下添加下。

**Comment by xiaohaiGreen** [comment]
已添加，更新到1.6试试

**Comment by Walleloveeve** [comment]
大佬你好，我在自己的NAS上更新到了最新版本。
在我的环境上测试，已经能正常获取到https和ipv6的种子链接，在qbittorrent上也能获取到rss链接并下载种子。
非常感谢！

`Linux nas 6.1.0-22-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64 GNU/Linux`
`qBittorrent v4.6.4 Web UI (64-bit)`
